version: '3'

services:
  assistant-mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=verySecretPassword
      - MONGO_INITDB_DATABASE=assistant
    ports:
      - 27017:27017

