spring:
  data:
    mongodb:
      username: root
      password: verySecretPassword
      host: 46.17.248.29
      port: 27017
      database: assistant

server:
  port: 8081
url-ms:
  email-receiver: "http://46.17.248.29:8082"

jwt:
  accessTokenExpirationMs: 600000
  refreshTokenExpirationMs: 1200000
  secret: very_very_secret_key@@very_very_secret_key+very_very_secret_key@@very_very_secret_key+very_very_secret_key@@very_very_secret_keyvery_very_secret_key@@very_very_secret_key+very_very_secret_key@@very_very_secret_key+very_very_secret_key@@very_very_secret_key
