spring:
  data:
    mongodb:
      username: root
      password: verySecretPassword
      host: localhost
      port: 27017
      database: assistant

server:
  port: 8081
url-ms:
  email-receiver: "http://localhost:8082"

jwt:
  accessTokenExpirationMs: 600000
  refreshTokenExpirationMs: 1200000
  secret: very_very_secret_key@@very_very_secret_key+very_very_secret_key@@very_very_secret_key+very_very_secret_key@@very_very_secret_keyvery_very_secret_key@@very_very_secret_key+very_very_secret_key@@very_very_secret_key+very_very_secret_key@@very_very_secret_key

telegram:
  bot:
    token: 5304570774:AAGxRHFWKrTQ7KrMHqMMbNIr3Q_UdFaDWY8
    name: Test-bot
